### ISSUE TITLE
USE flag system-icu not working on icedtea{,-bin}-7 but on oracle-jdk-bin-8

### ISSUE THREAD

**Issue by stefan-langenmaier** [gentoo/eclipse-overlay#6]
I investigated the problem from pull request #5 a little bit more.
The system-icu flag works with the oracle-jdk. The tests I did in the pull request were done with icedtea-bin.

**Comment by hartwork** [comment]
That's interesting. I wonder what to best do about it. What do you propose?

**Comment by stefan-langenmaier** [comment]
My issue report was wrong. It is possible to run Eclipse with icedtea. I put some more details in the issue #7.

Nevertheless I saw some differences between icedtea and oracle-jdk. When Eclipse is first started by icedtea the following will appear in the terminal:

```
$ eclipse-bin-4.5 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/stefan/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.0.20150526-2032.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://458.fwk1442077586:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://458.fwk1442077586:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
00:51:48,613 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
00:51:48,613 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
00:51:48,613 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
00:51:48,614 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
00:51:48,759 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
00:51:48,766 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/home/stefan/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.0.20150526-2032.xml]] every 60 seconds. 
00:51:48,766 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
00:51:48,767 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
00:51:48,767 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
00:51:48,866 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
00:51:48,869 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
00:51:48,897 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@4199320c - No compression will be used
00:51:48,922 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /home/stefan/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/0.log
00:51:48,923 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/home/stefan/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/0.log]
00:51:48,926 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eclipse.m2e.logback.appender.EclipseLogAppender]
00:51:48,926 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.eclipse.m2e.logback.appender.EclipseLogAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.EclipseLogAppender
    at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.EclipseLogAppender
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
    at  at java.util.TimerThread.mainLoop(Timer.java:555)
    at  at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.logback.appender.EclipseLogAppender cannot be found by ch.qos.logback.classic_1.0.7.v20121108-1250
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
    at  ... 17 common frames omitted
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@26:91 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.EclipseLogAppender
    at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.EclipseLogAppender
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:82)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
    at  at java.util.TimerThread.mainLoop(Timer.java:555)
    at  at java.util.TimerThread.run(Timer.java:505)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.EclipseLogAppender
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
    at  ... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.logback.appender.EclipseLogAppender cannot be found by ch.qos.logback.classic_1.0.7.v20121108-1250
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
    at  ... 17 common frames omitted
00:51:48,927 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eclipse.m2e.logback.appender.MavenConsoleAppender]
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.eclipse.m2e.logback.appender.MavenConsoleAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.MavenConsoleAppender
    at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.MavenConsoleAppender
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
    at  at java.util.TimerThread.mainLoop(Timer.java:555)
    at  at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.logback.appender.MavenConsoleAppender cannot be found by ch.qos.logback.classic_1.0.7.v20121108-1250
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
    at  ... 17 common frames omitted
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@32:98 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.MavenConsoleAppender
    at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.MavenConsoleAppender
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:82)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
    at  at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
    at  at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
    at  at java.util.TimerThread.mainLoop(Timer.java:555)
    at  at java.util.TimerThread.run(Timer.java:505)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.eclipse.m2e.logback.appender.MavenConsoleAppender
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:74)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:49)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
    at  at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
    at  ... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.logback.appender.MavenConsoleAppender cannot be found by ch.qos.logback.classic_1.0.7.v20121108-1250
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at  at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
    at  ... 17 common frames omitted
00:51:48,927 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
00:51:48,927 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
00:51:48,927 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [EclipseLog]. Did you define it below instead of above in the configuration file?
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [MavenConsoleLog]. Did you define it below instead of above in the configuration file?
00:51:48,927 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
00:51:48,928 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.ning.http.client] to INFO
00:51:48,928 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
00:51:48,928 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1dbca980 - Registering current configuration as safe fallback point

```

These errors will show up on the next start even if one changes the java-vm to oracle-jdk.

If upon the first start oracle-jdk is used the output is cleaner and will stay like this even when the jvm is later switched to icedtea:

```
$ eclipse-bin-4.5 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /home/stefan/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.0.20150526-2032.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://459.fwk575593575:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://459.fwk575593575:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
```

**Comment by stefan-langenmaier** [comment]
Closing it as it wasn't a valid report.

**Comment by stefan-langenmaier** [comment]
I propose to document as much as possible because I have no idea what the problem is. :)
